DROP TABLE IF EXISTS NOTES;

CREATE TABLE NOTES
(
  id VARCHAR
  AUTO_INCREMENT PRIMARY KEY,
  body VARCHAR (250) NOT NULL
);

DROP TABLE IF EXISTS TASKS;

CREATE TABLE TASKS
(
  id VARCHAR
  AUTO_INCREMENT PRIMARY KEY,
  parentId INT NOT NULL,
  taskTitle VARCHAR (250) NOT NULL,
  dueDate DATE NULL,
  status VARCHAR (250) NOT NULL
);